version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - demo-docker-network

  apidemodocker:
    build:
      dockerfile: ./demo-docker.dockerfile
      context: .
    image: guiferreirak/demo-docker-java
    ports:
      - "8080:8080"
    networks:
      - demo-docker-network
    depends_on:
      - "mongo"

networks:
  demo-docker-network:
    driver: bridge